/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiket.kereta.septina;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class frameMain extends javax.swing.JFrame {

    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jmlPenumpang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        stTujuan = new javax.swing.JTextField();
        stAsal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        comboTempatDuduk = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboJenis = new javax.swing.JComboBox<>();
        waktu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(230, 119, 15));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FORM CALON PENUMPANG");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(90, 0, 220, 40);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 370, 40);

        jLabel5.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("No ID");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 100, 130, 30);
        jPanel3.add(id);
        id.setBounds(10, 130, 350, 30);

        jLabel6.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Stasiun Tujuan");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 220, 130, 30);
        jPanel3.add(nama);
        nama.setBounds(10, 70, 350, 30);

        jLabel9.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Nama Pemesan");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 40, 130, 30);

        jLabel12.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Stasiun Asal");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 160, 130, 30);
        jPanel3.add(jmlPenumpang);
        jmlPenumpang.setBounds(10, 310, 350, 30);

        jLabel15.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Jumlah Penumpang");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 280, 160, 30);
        jPanel3.add(stTujuan);
        stTujuan.setBounds(10, 250, 350, 30);
        jPanel3.add(stAsal);
        stAsal.setBounds(10, 190, 350, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 130, 370, 350);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setLayout(null);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FORM CALON PENUMPANG");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(80, 0, 220, 40);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 0, 370, 40);

        jLabel7.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Jenis Kereta");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 100, 170, 30);
        jPanel4.add(Tanggal);
        Tanggal.setBounds(10, 70, 350, 30);

        jLabel10.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Tanggal Keberangkatan");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 40, 170, 30);

        comboTempatDuduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5", "Gerbong 6", "Gerbong 7" }));
        jPanel4.add(comboTempatDuduk);
        comboTempatDuduk.setBounds(10, 250, 350, 30);

        jLabel8.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Tempat duduk");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 220, 130, 30);

        jLabel13.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Waktu Berangkat");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 160, 130, 30);

        comboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penataran-Dhoho", "Malabar", "Gajayana" }));
        jPanel4.add(comboJenis);
        comboJenis.setBounds(10, 130, 350, 30);

        waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuActionPerformed(evt);
            }
        });
        jPanel4.add(waktu);
        waktu.setBounds(10, 190, 350, 30);

        jLabel14.setFont(new java.awt.Font("Swis721 Lt BT", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Harga");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 280, 130, 30);

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel4.add(harga);
        harga.setBounds(10, 310, 350, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(390, 130, 370, 350);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        btnPrint.setBackground(new java.awt.Color(1, 1, 84));
        btnPrint.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel8.add(btnPrint);
        btnPrint.setBounds(600, 10, 110, 30);

        btnSave.setBackground(new java.awt.Color(1, 1, 84));
        btnSave.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel8.add(btnSave);
        btnSave.setBounds(40, 10, 110, 30);

        btnDelete.setBackground(new java.awt.Color(1, 1, 84));
        btnDelete.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel8.add(btnDelete);
        btnDelete.setBounds(180, 10, 110, 30);

        btnRefresh.setBackground(new java.awt.Color(1, 1, 84));
        btnRefresh.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel8.add(btnRefresh);
        btnRefresh.setBounds(320, 10, 110, 30);

        btnClear.setBackground(new java.awt.Color(1, 1, 84));
        btnClear.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel8.add(btnClear);
        btnClear.setBounds(460, 10, 110, 30);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(10, 490, 750, 50);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NoID", "StasiunAsal", "StasiunTujuan", "JumlahPenumpang", "TanggalBerangkat", "JenisKereta", "WaktuBerangkat", "TempatDuduk", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 730, 120);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(10, 550, 750, 140);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("NewsGoth Cn BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMESANAN TIKET KERETA API");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(240, 20, 440, 50);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kenyamanan Anda Prioritas Kami");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, 70, 260, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\2.png")); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, -10, 200, 130);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 750, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 700);

        setSize(new java.awt.Dimension(786, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktuActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        
        if(nama.getText().equals("") || id.getText().equals("") || stAsal.getText().equals("") ||
                stTujuan.getText().equals("") || jmlPenumpang.getText().equals("") || tanggal.equals("") || 
                waktu.getText().equals("") ||  harga.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error",
                    JOptionPane.WARNING_MESSAGE);
        }
        else {
            
            String JK = "";
                if (comboJenis.getSelectedItem().equals("Penataran-Dhoho")){
                    JK = "Penataran-Dhoho";
                }else if(comboJenis.getSelectedItem().equals("Malabar")){
                    JK = "Malabar";
                }else {
                    JK = "Gajayana";
                }
                
            String TD = "";
                if (comboTempatDuduk.getSelectedItem().equals("Gerbong 1"))
                {
                    TD = "Gerbong 1";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 2")){
                    TD = "Gerbong 2";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 3")){
                    TD = "Gerbong 3";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 4")){
                    TD = "Gerbong 4";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 5")){
                    TD = "Gerbong 5";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 6")){
                    TD = "Gerbong 6";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 7")){
                    TD = "Gerbong 7";
                }
            String SQL = "INSERT INTO `penumpang` WHERE ('"+nama.getText()+"','"+id.getText()
                    +"', '"+stAsal.getText()+"', '"+stTujuan.getText()+"','"+jmlPenumpang.getText()
                    +"','"+tanggal+"','"+JK+"','"+waktu.getText()+"','"+TD+"', '"+harga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "GAGAL", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = Table.getSelectedRow();
        if (baris != -1) {
            String Nama = Table.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM `penumpang` WHERE Nama='"+Nama+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", " Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        id.setText("");
        stAsal.setText("");
        stTujuan.setText("");
        jmlPenumpang.setText("");
        waktu.setText("");
        harga.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Penumpang KAI");
        MessageFormat footer = new MessageFormat("Page {0, number, integer} ");
        try {
            Table.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } 
        catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboJenis;
    private javax.swing.JComboBox<String> comboTempatDuduk;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlPenumpang;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField stAsal;
    private javax.swing.JTextField stTujuan;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        //To change body of generated methods, choose Tools | Templates.
        String kolom[] = {"Nama","NoID","StasiunAsal","StasiunTujuan","JumlahPenumpang",
            "TanggalKeberangkatan","JenisKereta","WaktuBerangkat","TempatDuduk","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM `penumpang`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String Nama = rs.getString(1);
                String NoID = rs.getString(2);
                String StasiunAsal = rs.getString(3);
                String StasiunTujuan = rs.getString(4);
                String JumlahPenumpang = rs.getString(5);
                String TanggalKeberangkatan = rs.getString(6);
                String JenisKereta = "";
                if (comboJenis.getSelectedItem().equals("Penataran-Dhoho")){
                    JenisKereta = "Penataran-Dhoho";
                }else if(comboJenis.getSelectedItem().equals("Malabar")){
                    JenisKereta = "Malabar";
                }else {
                    JenisKereta = "Gajayana";
                }
                String WaktuBerangkat = rs.getString(8);
                 String TempatDuduk = "";
                if (comboTempatDuduk.getSelectedItem().equals("Gerbong 1"))
                {
                    TempatDuduk = "Gerbong 1";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 2")){
                    TempatDuduk = "Gerbong 2";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 3")){
                    TempatDuduk = "Gerbong 3";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 4")){
                    TempatDuduk = "Gerbong 4";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 5")){
                    TempatDuduk = "Gerbong 5";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 6")){
                    TempatDuduk = "Gerbong 6";
                }else if(comboTempatDuduk.getSelectedItem().equals("Gerbong 7")){
                    TempatDuduk = "Gerbong 7";
                }
                String Harga = rs.getString(10);
                String data[] = {Nama,NoID,StasiunAsal,StasiunTujuan,JumlahPenumpang,TanggalKeberangkatan,JenisKereta,WaktuBerangkat,TempatDuduk,Harga};
                dtm.addRow(data);
            }
                }catch (SQLException ex) {
                    Logger.getLogger(frameMain.class.getName()).log(Level.SEVERE, null, ex);
                }
        Table.setModel(dtm);
            }
    
}
